#ifndef SPI_CONFIG_FILE
#define SPI_CONFIG_FILE

//SPI_SLAVE_MODE AND SPI_MASTER_MODE
#define SPI_MCU_MODE (SPI_MASTER_MODE)

//SPI_ACTIVATE_POLLING_MODE AND SPI_ACTIVATE_INTERRUPT_MODE
#define SPI_INTERRUPT_MODE  (SPI_ACTIVATE_POLLING_MODE)

//SPI_CPOL_LOW_IDLE AND SPI_CPOL_HIGH_IDLE
#define SPI_CPOL_MODE  (SPI_CPOL_LOW_IDLE)

//SPI_CPHA_SAMPLE_LEADING AND SPI_CPHA_SAMPLE_LAGGING
#define SPI_CPHA_MODE (SPI_CPHA_SAMPLE_LEADING)

//SPI_DORD_MSB_FIRST AND SPI_DORD_LSB_FIRST
#define SPI_DORD_MODE  (SPI_DORD_MSB_FIRST)

//SPI_DEACTIVATE_DOUPLE_SPEED_MODE AND SPI_ACTIVATE_DOUPLE_SPEED_MODE
#define SPI_DOUBLE_SPEED_MODE (SPI_DEACTIVATE_DOUPLE_SPEED_MODE)

//SPI_PS_4, SPI_PS_16, SPI_PS_64, AND SPI_PS_128
#define SPI_PS (SPI_PS_128)

//SPI_EXTERNAL_ISR AND SPI_INTERNAL_ISR
#define SPI_ISR_STATUS  (SPI_INTERNAL_ISR)


#endif
