#ifndef TIMER1_CONFIG
#define TIMER1_CONFIG


#define TIMER1_WAVEFORM_GENERATION_MODE      (TIMER1_NORMAL)

#define TIMER1_INTERRUPT_MODE                (TIMER1_ACTIVATE_POLLING_MODE)

#define TIMER1_INPUT_CAPTURE_MODE              (TIMER1_ICU_RISING_EDGEs)

#define TIMER1_INPUT_CAPTURE_INTERRUPT_MODE   (TIMER1_DEACTIVATE_ICU_INTERRUPT)

#define TIMER1_CLOCK_SELECTION                  (TIMER1_PS_8)

#define TIMER1_NOISE_CANCELER_MODE                  (TIMER1_ACTIVATE_NC)


#endif